spring:
  application:
    name: helpdesk
#  Base de datos H2
#  datasource:
#    url: jdbc:h2:mem:inventorydb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000
  cache:
    type: redis
    redis:
      time-to-live: 60000


server:
  port: 8080